<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\MenuSetting;

class MenuSetupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $seeder = [
            [
                'code' => 'MPTT-H',
                'menu' => 'Home',
                'url' => '/payroll-and-timesheets/home',
                'icon' => 'home',
                'services_settings_id' => 2,
                'type' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-TR',
                'menu' => 'Time Records',
                'url' => '/payroll-and-timesheets/time-records/timelogs',
                'icon' => 'clock',
                'services_settings_id' => 2,
                'type' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-TR-TL',
                'menu' => 'Timelogs',
                'url' => '/payroll-and-timesheets/time-records/timelogs',
                'icon' => 'folderTab',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-TR-OT',
                'menu' => 'Overtime',
                'url' => '/payroll-and-timesheets/time-records/overtime',
                'icon' => 'clock',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-TR-H',
                'menu' => 'History',
                'url' => '/payroll-and-timesheets/time-records/history',
                'icon' => 'file',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-TR-M',
                'menu' => 'Monitoring',
                'url' => '/payroll-and-timesheets/time-records/monitoring',
                'icon' => 'radar',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-R',
                'menu' => 'Requests',
                'url' => '/payroll-and-timesheets/time-records/requests',
                'icon' => 'logRequest',
                'services_settings_id' => 2,
                'type' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-L',
                'menu' => 'Leaves',
                'url' => '/payroll-and-timesheets/time-records/leaves/credits',
                'icon' => 'leaveCredits',
                'services_settings_id' => 2,
                'type' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-L-LC',
                'menu' => 'Leave Credits',
                'url' => '/payroll-and-timesheets/time-records/leaves/credits',
                'icon' => 'calendarPlus',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-L-LC',
                'menu' => 'History',
                'url' => '/payroll-and-timesheets/time-records/leaves/history',
                'icon' => 'file',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-L-ML',
                'menu' => 'Manage Leaves',
                'url' => '/payroll-and-timesheets/time-records/leaves/manage',
                'icon' => 'settingKnot',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-P',
                'menu' => 'Payrolls',
                'url' => '/payroll-and-timesheets/time-records/payrolls/history',
                'icon' => 'payroll',
                'services_settings_id' => 2,
                'type' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-P-PH',
                'menu' => 'Payroll History',
                'url' => '/payroll-and-timesheets/time-records/payrolls/history',
                'icon' => 'file',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-P-PD',
                'menu' => 'Payroll Disputes',
                'url' => '/payroll-and-timesheets/time-records/payrolls/disputes',
                'icon' => 'payslip',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-P-MP',
                'menu' => 'Manage Payrolls',
                'url' => '/payroll-and-timesheets/time-records/payrolls/manage',
                'icon' => 'settingKnot',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-PS',
                'menu' => 'Payslips',
                'url' => '/payroll-and-timesheets/time-records/payslips/my-payslips',
                'icon' => 'payslip',
                'services_settings_id' => 2,
                'type' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-PS-P',
                'menu' => 'My Payslips',
                'url' => '/payroll-and-timesheets/time-records/payslips/my-payslips',
                'icon' => 'payslip',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-PS-H',
                'menu' => 'History',
                'url' => '/payroll-and-timesheets/time-records/payslips/history',
                'icon' => 'file',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-PS-MP',
                'menu' => 'Manage Payslip',
                'url' => '/payroll-and-timesheets/time-records/payslips/manage',
                'icon' => 'settingKnot',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-E',
                'menu' => 'Earnings',
                'url' => '/payroll-and-timesheets/time-records/earnings/my-earnings',
                'icon' => 'walletMoney',
                'type' => 1,
                'services_settings_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-E-ME',
                'menu' => 'My Earnings',
                'url' => '/payroll-and-timesheets/time-records/earnings/my-earnings',
                'icon' => 'creditCards',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-E-ME',
                'menu' => 'Manage Earnings',
                'url' => '/payroll-and-timesheets/time-records/earnings/manage',
                'icon' => 'settingKnot',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-D',
                'menu' => 'Deductions',
                'url' => '/payroll-and-timesheets/time-records/deductions/contributions',
                'icon' => 'deduction',
                'services_settings_id' => 2,
                'type' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-D-C',
                'menu' => 'Contributions',
                'url' => '/payroll-and-timesheets/time-records/deductions/contributions',
                'icon' => 'walletMinus',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-D-WT',
                'menu' => 'Withholding Tax',
                'url' => '/payroll-and-timesheets/time-records/deductions/withholding-tax',
                'icon' => 'math',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-D-OD',
                'menu' => 'Other Deductions',
                'url' => '/payroll-and-timesheets/time-records/deductions/others',
                'icon' => 'receiptMinus',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-D-MD',
                'menu' => 'Manage Deductions',
                'url' => '/payroll-and-timesheets/time-records/deductions/manage',
                'icon' => 'settingKnot',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-L',
                'menu' => 'Loans',
                'url' => '/payroll-and-timesheets/time-records/loans/history',
                'icon' => 'timeWallet',
                'services_settings_id' => 2,
                'type' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-L-LH',
                'menu' => 'Loan History',
                'url' => '/payroll-and-timesheets/time-records/loans/history',
                'icon' => 'calendarPlus',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-L-ML',
                'menu' => 'Manage Loan',
                'url' => '/payroll-and-timesheets/time-records/loans/history',
                'icon' => 'settingKnot',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-U',
                'menu' => 'Utilities',
                'url' => '/payroll-and-timesheets/time-records/utilities/withholding-tax-tables',
                'icon' => 'broom',
                'type' => 1,
                'services_settings_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-U-WTT',
                'menu' => 'Withholding Tax Table',
                'url' => '/payroll-and-timesheets/time-records/utilities/withholding-tax-tables',
                'icon' => null,
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-U-SST',
                'menu' => 'SSS Table',
                'url' => '/payroll-and-timesheets/time-records/utilities/sss-contribution-tables',
                'icon' => null,
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-U-PT',
                'menu' => 'Philhealth Table',
                'url' => '/payroll-and-timesheets/time-records/utilities/philhealth-contribution-tables',
                'icon' => null,
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-U-HDMFT',
                'menu' => 'Philhealth Table',
                'url' => '/payroll-and-timesheets/time-records/utilities/hdmf-contribution-tables',
                'icon' => null,
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-U-GSIST',
                'menu' => 'GSIS Table',
                'url' => '/payroll-and-timesheets/time-records/utilities/gsis-contribution-tables',
                'icon' => null,
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-S',
                'menu' => 'Setup',
                'url' => '/payroll-and-timesheets/time-records/setup/payroll',
                'icon' => null,
                'type' => 1,
                'services_settings_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-S-P',
                'menu' => 'Payroll',
                'url' => '/payroll-and-timesheets/time-records/setup/payroll',
                'icon' => 'payroll',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-S-L',
                'menu' => 'Leaves',
                'url' => '/payroll-and-timesheets/time-records/setup/leaves',
                'icon' => 'calendarPlus',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-S-CO',
                'menu' => 'Cut-Offs',
                'url' => '/payroll-and-timesheets/time-records/setup/cut-offs',
                'icon' => 'calendar',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-S-S',
                'menu' => 'Shifts',
                'url' => '/payroll-and-timesheets/time-records/setup/shifts',
                'icon' => 'hour',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MPTT-S-E',
                'menu' => 'Employee',
                'url' => '/payroll-and-timesheets/time-records/setup/employee',
                'icon' => 'resource',
                'services_settings_id' => 2,
                'type' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        MenuSetting::insert($seeder);
    }
}
