<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\PayrollAndTimesheets\Setup\PayrollSetting;

class PayrollSetupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $seeder = [
            [
                'abbrev' => 'PhilHealth',
                'name' => 'PhilHealth',
                'type' => 1,
                'is_fixed' => 0,
                'amount' => 0,
                'is_percentage' => 0,
                'subject_for_tax' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'SSS',
                'name' => 'SSS',
                'type' => 1,
                'is_fixed' => 0,
                'amount' => 0,
                'is_percentage' => 0,
                'subject_for_tax' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'GSIS',
                'name' => 'GSIS',
                'type' => 1,
                'is_fixed' => 0,
                'amount' => 0,
                'is_percentage' => 0,
                'subject_for_tax' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'HDMF',
                'name' => 'HDMF',
                'type' => 1,
                'is_fixed' => 0,
                'amount' => 0,
                'is_percentage' => 0,
                'subject_for_tax' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'HMO',
                'name' => 'HMO Share',
                'type' => 2,
                'is_fixed' => 0,
                'amount' => 0,
                'is_percentage' => 0,
                'subject_for_tax' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'Tax',
                'name' => 'Withholding Tax',
                'type' => 3,
                'is_fixed' => 0,
                'amount' => 0,
                'is_percentage' => 0,
                'subject_for_tax' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'Tardiness',
                'name' => 'Tardiness',
                'type' => 2,
                'is_fixed' => 0,
                'amount' => 0,
                'is_percentage' => 0,
                'subject_for_tax' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'PA (Ded.)',
                'name' => 'Payroll Adjustment (Ded.)',
                'type' => 2,
                'is_fixed' => 0,
                'amount' => 0,
                'is_percentage' => 0,
                'subject_for_tax' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'Other (Ded.)',
                'name' => 'Other Deduction',
                'type' => 4,
                'is_fixed' => 0,
                'amount' => 0,
                'is_percentage' => 0,
                'subject_for_tax' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'Basic Pay',
                'name' => 'Basic Pay',
                'type' => 5,
                'is_fixed' => 0,
                'amount' => 0,
                'is_percentage' => 0,
                'subject_for_tax' => 0,
                'subject_for_tax' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'Hourly Rate',
                'name' => 'Hourly Rate',
                'type' => 5,
                'is_fixed' => 0,
                'amount' => 0,
                'is_percentage' => 0,
                'subject_for_tax' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'RD OT',
                'name' => 'Rest Day OT',
                'type' => 6,
                'is_fixed' => 1,
                'amount' => 30,
                'is_percentage' => 1,
                'subject_for_tax' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'Holiday OT',
                'name' => 'Holiday OT',
                'type' => 6,
                'is_fixed' => 1,
                'amount' => 30,
                'is_percentage' => 1,
                'subject_for_tax' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => '13th Month',
                'name' => '13th Month Pay',
                'type' => 6,
                'is_fixed' => 0,
                'amount' => 0,
                'is_percentage' => 0,
                'subject_for_tax' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'Bonus',
                'name' => 'Bonus',
                'type' => 6,
                'is_fixed' => 0,
                'amount' => 0,
                'is_percentage' => 0,
                'subject_for_tax' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'Allowance',
                'name' => 'Allowance',
                'type' => 6,
                'is_fixed' => 0,
                'amount' => 0,
                'is_percentage' => 0,
                'subject_for_tax' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'De minimis',
                'name' => 'De minimis',
                'type' => 6,
                'is_fixed' => 1,
                'amount' => 2500,
                'is_percentage' => 0,
                'subject_for_tax' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'Night Diff.',
                'name' => 'Night Differential',
                'type' => 6,
                'is_fixed' => 1,
                'amount' => 10,
                'is_percentage' => 1,
                'subject_for_tax' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'Hazard Pay',
                'name' => 'Hazard Pay',
                'type' => 6,
                'is_fixed' => 1,
                'amount' => 1000,
                'is_percentage' => 0,
                'subject_for_tax' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'PA (Earn.)',
                'name' => 'Payroll Adjustment (Earnings)',
                'type' => 6,
                'is_fixed' => 0,
                'amount' => 0,
                'is_percentage' => 0,
                'subject_for_tax' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'abbrev' => 'Other (Earn.)',
                'name' => 'Other Earnings',
                'type' => 2,
                'is_fixed' => 0,
                'amount' => 0,
                'is_percentage' => 0,
                'subject_for_tax' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        PayrollSetting::insert($seeder);
    }
}
